# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659675700d870525e69f6dc318e1cd6a993222445b0b0188cc0a8acd9711b99dc5f13f706034554dacbf36ca61ae6911e4979f075aeda17e751545626b056a49

test:
  secret_key_base: 661eb4737a16fec4ed84c60319d2c777976695e19abc98fc1fc42c5e0449ee040327eb07d71e9f431364dbba3846bf730447731cee6bde0cbe3a11a7acc21e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
